**[Slide No. 5]**

1. Write a Program to check the version numpy installed .

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


**[Slide No . 8]**

2. Write a program to create numpy 1-D array from list.

In [2]:
import numpy as np

In [3]:
x=[10,20,30]
np.array(x)

array([10, 20, 30])

**[Slide No. 9]**

3. Write a program to Create a 2-D array .

In [4]:
sss=np.array([[1,2,3],
            [10,20,30],
            [11,12,13]])
sss

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 12, 13]])

In [5]:
nn=np.random.randint(100,size=(3,4))
nn

array([[57, 64, 81, 47],
       [27, 89, 92, 71],
       [ 1,  6, 52, 19]])

**[Slide No . 11]**

5. a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])



What is the output [5 9] ?

In [6]:
a=np.array([(1,2,3,4),
            (3,4,5,6),
            (7,8,9,10)])
print(a[1:,2]) #(rows,columns)

[5 9]


**[Slide No.15]**

6. Correct the program .

import numpy as np

array=np.array([1,2,3,4,5,6])

print(array[-1:-5])

In [7]:
array = np.array([1,2,3,4,5,6])

print(array[-5:-1])

[2 3 4 5]


7. a=np.array([(1,5,9),(10,12,2),(5,7,8)])


Print the max value from first row ?

print min value from the first row ?

print the sum of all the element of second row ?




In [8]:
a=np.array([(1,5,9),
           (10,12,2),
           (5,7,8)])
np.max(a[0,:])
np.min(a[0,:])
np.sum(a[1,:])

24

In [9]:
a=np.array([(1,5,9),(10,12,2),(5,7,8)])
a

array([[ 1,  5,  9],
       [10, 12,  2],
       [ 5,  7,  8]])

In [10]:
import numpy as np
np1=np.random.randint(2,9,(3,2,3,4))
np1.ndim

4

In [11]:
np1[0].sum()

137

**[Slide No. 16]**


8. Create a numpy array using a below numbers and print (1,3,5).

[1,2,3,4,5,6]



In [12]:
x1=np.array([[1,2],
           [3,4],
           [5,6]])
print(x1[0:,:1])

[[1]
 [3]
 [5]]


**[Slide No. 18]**

9. Create a  [3,4] numpy array and reshape it [4,3] numpy array.

In [16]:
nn=np.random.randint(100,size=(3,4))
nn

array([[49, 96, 18, 11],
       [87, 39, 23, 28],
       [95, 82, 69, 69]])

In [17]:
nn1=nn.reshape(4,3)
nn1

array([[49, 96, 18],
       [11, 87, 39],
       [23, 28, 95],
       [82, 69, 69]])

**[Slide No. 20]**

10. Create two numpy array and concanate them .

In [18]:
nn=np.random.randint(100,size=(2,10))
nn1=np.random.randint(100,size=(2,10))
print(nn)
print(nn1)

np.vstack((nn,nn1))

[[17 23 58  4  7 42 81 13 59 63]
 [87 95 38 36 48 26 45 89 11 66]]
[[ 5 55 33 17 82 24 90 47 53 33]
 [77 30 49 17 34 92 67 85 19 10]]


array([[17, 23, 58,  4,  7, 42, 81, 13, 59, 63],
       [87, 95, 38, 36, 48, 26, 45, 89, 11, 66],
       [ 5, 55, 33, 17, 82, 24, 90, 47, 53, 33],
       [77, 30, 49, 17, 34, 92, 67, 85, 19, 10]])

In [19]:
nn=np.random.randint(100,size=(2,10))
nn1=np.random.randint(100,size=(2,10))
print(nn)
print(nn1)

np.hstack((nn,nn1))

[[55 22 93 79 80 31 31  3  4 62]
 [80 17 37 89 10 75 28 36 27 51]]
[[28 21 33 77 42 59 68 48 30 26]
 [71  7 40 53 93 96 91 39 18 41]]


array([[55, 22, 93, 79, 80, 31, 31,  3,  4, 62, 28, 21, 33, 77, 42, 59,
        68, 48, 30, 26],
       [80, 17, 37, 89, 10, 75, 28, 36, 27, 51, 71,  7, 40, 53, 93, 96,
        91, 39, 18, 41]])

**[Slide No.22]**

11. Create numpy array and search a number in it .

In [20]:
a=np.arange(0,5)
np.where(a==4)

(array([4], dtype=int64),)

In [21]:
nn=np.random.randint(100,size=(2,10))
nn

array([[45, 52, 30, 38, 81, 14, 75, 24, 25, 86],
       [56, 14, 53, 87, 67, 32, 92, 53, 17, 84]])

In [22]:
np.where(nn==81)

(array([0], dtype=int64), array([4], dtype=int64))

**[Slide No.26]**

12. Write a program to print 3,4 numpy array by any random number using random.randint function

**[Slide No. 30]**

13. Write a program to add two numpy array.

14. Delete the second column from a given array and insert the following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])

In [23]:
import numpy as np


In [24]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis = 0)
print(sampleArray)
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 0)
#print(sampleArray)

[[34 43 73]
 [53 94 66]]


In [25]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [26]:
sampleArray[:,1]=[10,10,10]

In [27]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])